# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-08 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200108_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_institution',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user_purpose',
            new_name='purpose',
        ),
    ]
